### ISSUE TITLE
go wrong when click a link with data-comfirm  , error seems from  fix_bootstrap.js

### ISSUE THREAD

**Issue by openxyz** [thooams/Ui-Bibz#52]
when click a link wtih data-confirm like below:
```html
<a data-method="delete" data-confirm="Are u sure?" class="dropdown-item" href="/auth/logout">logout</a>
```

browser will go to a  http get requeset of "/auth/logout" if i choose cancel 

the error seems from `https://github.com/thooams/Ui-Bibz/blob/master/app/assets/javascripts/fix_bootstrap.coffee`
```javascript
# Fix for button link in button group
$(document).on 'turbolinks:load page:change ready', ->
  $('.btn-group > a.btn, .dropdown-item').click ->
    try # Turbolinks exist
      Turbolinks.visit($(this).attr('href'))
    catch exception # Turbolinks doesn't exist
      window.location = $(this).attr('href')
```

the last line code run and make wrong behavior  because i don`t use turbolinks 

it seems to no need to include the code above for now

**Comment by thooams** [comment]
Update your Gemfile to 2.3.10.
